- name: mkfs.{{fileSystemType}} {{diskDir}}
  command: mkfs.{{fileSystemType}} -f {{diskDir}}
- name: mkdir /tmp/datanode -p
  command: mkdir /tmp/datanode -p
- name: cp datanode backup
  shell: cp -R {{mountDir}}/* /tmp/datanode
- name: mount {{diskDir}} {{mountDir}}
  command: mount {{diskDir}} {{mountDir}}
- name: vi /etc/fstab
  shell: echo {{item}} >> /etc/fstab
  with_items: 
  - \{{diskDir}}\  \{{mountDir}}\ \{{fileSystemType}}\ defaults 0 0
- name: mv backup to {{mountDir}}
  shell: mv /tmp/datanode/*  {{mountDir}}
- name: file owrm
  file: path={{mountDir}}  owner=hdfs group=hadoop mode=755
- name: drop /tmp/datanode
  command: rm -rf tmp/datanode
