---
- hosts: hdp-1
  tasks: 
  - name: authorized_keys
    become: yes
    become_method: sudo
    authorized_key:
                   key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
                   state=present

#gfkjsdhglfkjjjjjjjjjjjjjjjjjjjj